import { createElement } from 'lwc';
import FlowRedirectURL from 'c/flowRedirectURL';

describe('c-flow-redirect-url', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-flow-redirect-url', {
            is: FlowRedirectURL
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    /*it('should open the correct URL in a new tab', () => {
        const URL = 'lightning/o/OffreEmploi__c/new';
        const TARGET = '_blank';
        const expectedURL = `${window.location.origin}/${URL}`;

        const element = createElement('c-flow-redirect-url', {
            is: FlowRedirectURL
        });
        element.url = URL;
        element.target = TARGET;
        document.body.appendChild(element);

        return Promise.resolve()
            .then(() => {
                //expect(window.open).toHaveBeenCalledTimes(1);
                expect(window.open).toHaveBeenCalledWith(expectedURL, TARGET);
            })
            .finally(() => {
                document.body.removeChild(element);
            });
    });*/
});